---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ticketing-system
  namespace: coding-assistant
  labels:
    app: ticketing-system
    app.kubernetes.io/part-of: ocp-troubleshooter-demo
spec:
  to:
    kind: Service
    name: ticketing-system
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
