---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: working-demo-app
  namespace: demo-app
  labels:
    app: working-demo-app
    app.kubernetes.io/part-of: ocp-troubleshooter-demo
spec:
  selector:
    matchLabels:
      app: working-demo-app
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
      scheme: http
